### ISSUE TITLE
FillEntityWithXml 方法存在缺陷，未处理好  component_verify_ticket 类型的数据转换

### ISSUE THREAD

**Issue by hebiziyu** [Senparc/NeuChar#1]
00:13:28.422  9 W - Senparc.Weixin.Exceptions.WeixinException: RequestMessage转换出错！可能是InfoType不存在！，XML：<xml>
  <AppId><![CDATA[wx7d63acd947266XXXX]]></AppId>
  <CreateTime>1536250407</CreateTime>
  <InfoType><![CDATA[component_verify_ticket]]></InfoType>
  <ComponentVerifyTicket><![CDATA[ticket@@@kyLY-XFJaFlQZVOF_ny7CWo2fr0tPz7KRKwUZi2HgzdLvfK1bh_SfCIRcmcC5OO0leZF7ZuySCtecipOrLbQPw]]></ComponentVerifyTicket>
</xml> ---> System.ArgumentException: 未找到属性设置方法。
   在 System.Reflection.RuntimePropertyInfo.SetValue(Object obj, Object value, BindingFlags invokeAttr, Binder binder, Object[] index, CultureInfo culture)
   在 System.Reflection.RuntimePropertyInfo.SetValue(Object obj, Object value, Object[] index)
   在 Senparc.NeuChar.Helpers.EntityHelper.FillEntityWithXml[T](T entity, XDocument doc)
   在 Senparc.Weixin.Open.RequestMessageFactory.GetRequestEntity(XDocument doc, PostModel postModel)

**Comment by JeffreySu** [comment]
我也发现了，马上会进行处理。

**Comment by JeffreySu** [comment]
@hebiziyu 你能跟踪到是哪一个类型吗？

**Comment by hebiziyu** [comment]
component_verify_ticket

**Comment by hebiziyu** [comment]
@JeffreySu component_verify_ticket

**Comment by JeffreySu** [comment]
已经修复，单元测试已通过。感谢！

NeuChar 版本号：v0.0.6.10，Open版本号：v4.1.3

![image](https://user-images.githubusercontent.com/2281927/45222752-ebea7200-b2e7-11e8-96af-c9b1f0e2e8b2.png)
