### ISSUE TITLE
Keyword没有支持Fun<Task<IResponseMessageBase>>?只有Default支持？

### ISSUE THREAD

**Issue by lcb1208** [Senparc/NeuChar#113]

**Comment by JeffreySu** [comment]
没理解，您要问什么问题？

**Comment by lcb1208** [comment]
> 没理解，您要问什么问题？
 
![image](https://user-images.githubusercontent.com/14539177/96816857-a4d08400-1450-11eb-8478-39e0293e4fa5.png)


像这样的，会提示lambda无法转化成Fun<IResponseMessageBase>.

 public override async Task<IResponseMessageBase> OnTextRequestAsync(RequestMessageText requestMessage)
        {
            var defaultResponseMessage = base.CreateResponseMessage<ResponseMessageText>();
            var requestHandler = await requestMessage.StartHandler().Keyword("1232",async()=>{ 
                                  string resultMsg= await method();
                                 defaultResponseMessage.Content=resultMsg;
                                 return  defaultResponseMessage;
})

**Comment by lcb1208** [comment]
default支持了Fun<Task<IResponseMessageBase>>.
还是说我用的不对。。。

**Comment by lcb1208** [comment]
用default替代了，是否加个keyword支持Fun<Task<IResponseMessageBase>>

**Comment by JeffreySu** [comment]
好像您没有理解这个用法，最后加一个.Default()是必须的，不是类型的问题，是您的代码没有写完整。

**Comment by lcb1208** [comment]
` public override async Task<IResponseMessageBase> OnTextRequestAsync(RequestMessageText requestMessage)
        {
            var defaultResponseMessage = base.CreateResponseMessage<ResponseMessageText>();
            var requestHandler = await requestMessage.StartHandler()
                //关键字不区分大小写，按照顺序匹配成功后将不再运行下面的逻辑
                .Keywords(new[] { "你好", "您好", "hi", "hello" }, () =>
                {
                    defaultResponseMessage.Content = "您好，请问有什么可以帮您？";
                    return defaultResponseMessage;
                }) 
               **.Keywords(“异步”, async() =>
                {
                    string result=    await Dosometing();
                    defaultResponseMessage.Content = result;
                    return defaultResponseMessage;
                })** 
              .Default(async () =>
                { 
                        defaultResponseMessage.Content = “123”;
                        return defaultResponseMessage; 
                });`
private aync Task<string> Dosometing(){
await Task.Completed;
return "111"
}

**Comment by JeffreySu** [comment]
Default 是必须的，因为可能你并没有处理掉所有可能出现的RequestType，类似switch的道理。参考Demo里面如何返回就行了。
