### ISSUE TITLE
没有捕获的异常

### ISSUE THREAD

**Issue by xjaja** [Senparc/NeuChar#114]
https://github.com/Senparc/NeuChar/blob/b6e5e0f92fef03fc8f09a90fccdab4a834ab10d6/src/Senparc.NeuChar/MessageHandlers/MessageHandler.SaveLog.cs#L104

开启
`messageHandler.SaveResponseMessageLog();//记录 Response 日志（可选）`

当发送过来的消息是加密的时候这里会报 NullReferenceException 。

**Comment by JeffreySu** [comment]
@xjaja 你的输入的XML的日志可以发一下吗？

**Comment by xjaja** [comment]
`<xml>
    <ToUserName><![CDATA[wx41ca876f0d7dbf12]]></ToUserName>
    <Encrypt><![CDATA[+IG3Nvwhymnx5PeD6QTle31Ngny+EOMF6UGQkyo1QsoehpdSXkTAMXPx39g8S7/WNwz5L9zPxJ4e3WxUlp2SwWwVXROh2vrdPtBGDHuoiApXucrsvoKCJ25pY2A62/MDhS51mr1ksZtSRq6ERK6LFMJxHMm3fr/g1EkApykNgwxDJLTyqTl1r51TF/PSu2T84R7ntgqqwCdY4bpN77WUf7qtA+X1evtxtHrhwwIlh3fuNSEe8M5jkciGFoUwM4d4xuv6MAWDqINqrrgKrLYoaGtRxOsLpGK9JYwMSbjjQpOHhRhq8OUcqTh7cHUnhluCL/89JtUOCQUXGlZZE1gv+ESKyH21N8mKUibiY1lxiTK2YlBPcv2ppAxHrk4pSKcBGOxeRLHnPI0m3HW36+CeCtTV16+ZTqQRx/W8GS3NosgueqE17FH+h9VCmv71RxxtX5+CtaGiLPuZZXc7sjiEyNrbwlZWyL23Lqpp3dH47gREcB0zPqQNpH5m6Jb33Rv3]]></Encrypt>
</xml>
`

https://github.com/Senparc/NeuChar/blob/b6e5e0f92fef03fc8f09a90fccdab4a834ab10d6/src/Senparc.NeuChar/MessageHandlers/MessageHandler.SaveLog.cs#L90-L95


https://github.com/Senparc/NeuChar/blob/b6e5e0f92fef03fc8f09a90fccdab4a834ab10d6/src/Senparc.NeuChar/MessageHandlers/MessageHandler.SaveLog.cs#L102-L107

上面未加密部分处理了，下面加密的没处理

**Comment by JeffreySu** [comment]
> `<xml> <ToUserName><![CDATA[wx41ca876f0d7dbf12]]></ToUserName> <Encrypt><![CDATA[+IG3Nvwhymnx5PeD6QTle31Ngny+EOMF6UGQkyo1QsoehpdSXkTAMXPx39g8S7/WNwz5L9zPxJ4e3WxUlp2SwWwVXROh2vrdPtBGDHuoiApXucrsvoKCJ25pY2A62/MDhS51mr1ksZtSRq6ERK6LFMJxHMm3fr/g1EkApykNgwxDJLTyqTl1r51TF/PSu2T84R7ntgqqwCdY4bpN77WUf7qtA+X1evtxtHrhwwIlh3fuNSEe8M5jkciGFoUwM4d4xuv6MAWDqINqrrgKrLYoaGtRxOsLpGK9JYwMSbjjQpOHhRhq8OUcqTh7cHUnhluCL/89JtUOCQUXGlZZE1gv+ESKyH21N8mKUibiY1lxiTK2YlBPcv2ppAxHrk4pSKcBGOxeRLHnPI0m3HW36+CeCtTV16+ZTqQRx/W8GS3NosgueqE17FH+h9VCmv71RxxtX5+CtaGiLPuZZXc7sjiEyNrbwlZWyL23Lqpp3dH47gREcB0zPqQNpH5m6Jb33Rv3]]></Encrypt> </xml> `
> 
> https://github.com/Senparc/NeuChar/blob/b6e5e0f92fef03fc8f09a90fccdab4a834ab10d6/src/Senparc.NeuChar/MessageHandlers/MessageHandler.SaveLog.cs#L90-L95
> 
> https://github.com/Senparc/NeuChar/blob/b6e5e0f92fef03fc8f09a90fccdab4a834ab10d6/src/Senparc.NeuChar/MessageHandlers/MessageHandler.SaveLog.cs#L102-L107
> 
> 上面未加密部分处理了，下面加密的没处理

需要发一下解密后的。

**Comment by xjaja** [comment]
> > `<xml> <ToUserName><![CDATA[wx41ca876f0d7dbf12]]></ToUserName> <Encrypt><![CDATA[+IG3Nvwhymnx5PeD6QTle31Ngny+EOMF6UGQkyo1QsoehpdSXkTAMXPx39g8S7/WNwz5L9zPxJ4e3WxUlp2SwWwVXROh2vrdPtBGDHuoiApXucrsvoKCJ25pY2A62/MDhS51mr1ksZtSRq6ERK6LFMJxHMm3fr/g1EkApykNgwxDJLTyqTl1r51TF/PSu2T84R7ntgqqwCdY4bpN77WUf7qtA+X1evtxtHrhwwIlh3fuNSEe8M5jkciGFoUwM4d4xuv6MAWDqINqrrgKrLYoaGtRxOsLpGK9JYwMSbjjQpOHhRhq8OUcqTh7cHUnhluCL/89JtUOCQUXGlZZE1gv+ESKyH21N8mKUibiY1lxiTK2YlBPcv2ppAxHrk4pSKcBGOxeRLHnPI0m3HW36+CeCtTV16+ZTqQRx/W8GS3NosgueqE17FH+h9VCmv71RxxtX5+CtaGiLPuZZXc7sjiEyNrbwlZWyL23Lqpp3dH47gREcB0zPqQNpH5m6Jb33Rv3]]></Encrypt> </xml> `
> > https://github.com/Senparc/NeuChar/blob/b6e5e0f92fef03fc8f09a90fccdab4a834ab10d6/src/Senparc.NeuChar/MessageHandlers/MessageHandler.SaveLog.cs#L90-L95
> > 
> > https://github.com/Senparc/NeuChar/blob/b6e5e0f92fef03fc8f09a90fccdab4a834ab10d6/src/Senparc.NeuChar/MessageHandlers/MessageHandler.SaveLog.cs#L102-L107
> > 
> > 上面未加密部分处理了，下面加密的没处理
> 
> 需要发一下解密后的。

没有解密就异常了。

https://mp.weixin.qq.com/debug/

接受文本消息，微信发送过来的消息使用本地密钥解密失败时记录请求日志就会异常。

**Comment by JeffreySu** [comment]
@xjaja 有一种可能是没有解密成功。您是公众号还是小程序或其他？

**Comment by JeffreySu** [comment]
长时间没有答复，先关闭了。
