### ISSUE TITLE
企业微信第三方应用开发，返回的数据没有包含MsgId，CreateTime 被标记为重复消息， 事件不能触发

### ISSUE THREAD

**Issue by zxz524** [Senparc/NeuChar#121]
https://github.com/Senparc/NeuChar/blob/940ff3c0d8c118a3df4b51dc559c4e43d69f0482/src/Senparc.NeuChar/MessageHandlers/MessageHandler.cs#L566

企业微信第三方应用开发，返回的数据没有包含MsgId，CreateTime 导致CancelExcute=True，微信推送过来的消息永远被标记为重复，相关事件不能触发！

跟踪调试输出的日志：

[[[系统日志]]]
[2021/03/25 12:14:16.2526]
[线程：6]
消息去重
lastMessage.MsgId=0,RequestMessage.MsgId=0
lastMessage.CreateTime=0001/1/1 0:00:00 +00:00,RequestMessage.CreateTime=0001/1/1 0:00:00 +00:00
lastMessage.MsgType=Event,RequestMessage.MsgType=Event

**Comment by JeffreySu** [comment]
@zxz524 有没有你接收到消息的xml发上来一下？

**Comment by zxz524** [comment]
<xml&gt;
&nbsp; <SuiteId&gt;<![CDATA[ww9a26d8dd96de2ca9]]&gt;</SuiteId&gt;
&nbsp; <AuthCorpId&gt;<![CDATA[wx52e8f516b7e12b16]]&gt;</AuthCorpId&gt;
&nbsp; <InfoType&gt;<![CDATA[change_external_contact]]&gt;</InfoType&gt;
&nbsp; <TimeStamp&gt;1616645656</TimeStamp&gt;
&nbsp; <ChangeType&gt;<![CDATA[add_external_contact]]&gt;</ChangeType&gt;
&nbsp; <UserID&gt;<![CDATA[ST10002]]&gt;</UserID&gt;
&nbsp; <ExternalUserID&gt;<![CDATA[wmlcoYBwAA2T7F7Lk0FJToRQkOb5y1JQ]]&gt;</ExternalUserID&gt;
&nbsp; <WelcomeCode&gt;<![CDATA[92Kbz3iHNUhMJOXR29exzWWZvuv9iAqPSDDGFlFsrTY]]&gt;</WelcomeCode&gt;
</xml&gt;

&nbsp;

JasonZhou


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Jeffrey ***@***.***&gt;; 
发送时间: 2021年3月25日(星期四) 下午3:29
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Senparc/NeuChar] 企业微信第三方应用开发，返回的数据没有包含MsgId，CreateTime 被标记为重复消息， 事件不能触发 (#121)





 
@zxz524 有没有你接收到消息的xml发上来一下？

**Comment by zxz524** [comment]
<xml&gt;
&nbsp; <SuiteId&gt;<![CDATA[ww9a26d8dd96de2ca9]]&gt;</SuiteId&gt;
&nbsp; <AuthCorpId&gt;<![CDATA[wx52e8f516b7e12b16]]&gt;</AuthCorpId&gt;
&nbsp; <InfoType&gt;<![CDATA[change_external_contact]]&gt;</InfoType&gt;
&nbsp; <TimeStamp&gt;1616645656</TimeStamp&gt;
&nbsp; <ChangeType&gt;<![CDATA[add_external_contact]]&gt;</ChangeType&gt;
&nbsp; <UserID&gt;<![CDATA[ST10002]]&gt;</UserID&gt;
&nbsp; <ExternalUserID&gt;<![CDATA[wmlcoYBwAA2T7F7Lk0FJToRQkOb5y1JQ]]&gt;</ExternalUserID&gt;
&nbsp; <WelcomeCode&gt;<![CDATA[92Kbz3iHNUhMJOXR29exzWWZvuv9iAqPSDDGFlFsrTY]]&gt;</WelcomeCode&gt;
</xml&gt;




JasonZhou


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Senparc/NeuChar"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月25日(星期四) 下午3:29
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Senparc/NeuChar] 企业微信第三方应用开发，返回的数据没有包含MsgId，CreateTime 被标记为重复消息， 事件不能触发 (#121)





 
@zxz524 有没有你接收到消息的xml发上来一下？

**Comment by zxz524** [comment]
https://github.com/Senparc/NeuChar/blob/940ff3c0d8c118a3df4b51dc559c4e43d69f0482/src/Senparc.NeuChar/Entities/Base/Request/RequestMessageBase.cs#L59
在这个位置给初始值，好像可以解决问题，但不知道会不有其他问题！
            MsgId = SystemTime.NowTicks;
            CreateTime = SystemTime.Now;

**Comment by JeffreySu** [comment]
> https://github.com/Senparc/NeuChar/blob/940ff3c0d8c118a3df4b51dc559c4e43d69f0482/src/Senparc.NeuChar/Entities/Base/Request/RequestMessageBase.cs#L59
> 
> 
> 在这个位置给初始值，好像可以解决问题，但不知道会不有其他问题！
> MsgId = SystemTime.NowTicks;
> CreateTime = SystemTime.Now;

我来从根本上处理一下吧

**Comment by JeffreySu** [comment]
> https://github.com/Senparc/NeuChar/blob/940ff3c0d8c118a3df4b51dc559c4e43d69f0482/src/Senparc.NeuChar/Entities/Base/Request/RequestMessageBase.cs#L59
> 
> 
> 在这个位置给初始值，好像可以解决问题，但不知道会不有其他问题！
> MsgId = SystemTime.NowTicks;
> CreateTime = SystemTime.Now;

我来从根本上处理一下吧

**Comment by JeffreySu** [comment]
> https://github.com/Senparc/NeuChar/blob/940ff3c0d8c118a3df4b51dc559c4e43d69f0482/src/Senparc.NeuChar/Entities/Base/Request/RequestMessageBase.cs#L59
> 
> 
> 在这个位置给初始值，好像可以解决问题，但不知道会不有其他问题！
> MsgId = SystemTime.NowTicks;
> CreateTime = SystemTime.Now;

我来从根本上处理一下吧

**Comment by JeffreySu** [comment]
> https://github.com/Senparc/NeuChar/blob/940ff3c0d8c118a3df4b51dc559c4e43d69f0482/src/Senparc.NeuChar/Entities/Base/Request/RequestMessageBase.cs#L59
> 
> 
> 在这个位置给初始值，好像可以解决问题，但不知道会不有其他问题！
> MsgId = SystemTime.NowTicks;
> CreateTime = SystemTime.Now;

我来从根本上处理一下吧

**Comment by JeffreySu** [comment]
已处理，请更新到最新版本。
