### ISSUE TITLE
CheckMessageRepeat 里时间比较报错

### ISSUE THREAD

**Issue by qucc** [Senparc/NeuChar#125]
![image](https://user-images.githubusercontent.com/1032477/114984088-f3bd1a80-9ec3-11eb-8fb7-5c3a74b86e4f.png)

测试代码
```
 if(DateTimeOffset.Now!= DateTime.MinValue)
    {

    }
System.ArgumentOutOfRangeException:“The UTC time represented when the offset is applied must be between year 0 and 10,000. 
```

**Comment by JeffreySu** [comment]
@qucc 请更新到最新的代码，之前已经改过了：

https://github.com/Senparc/NeuChar/blob/6063ded21f2aa1d2a97aef2348c70dd682ffa9ad/src/Senparc.NeuChar/MessageHandlers/MessageHandler.cs#L579

感谢！
