### ISSUE TITLE
企业微信，消息去重存在严重bug

### ISSUE THREAD

**Issue by zxz524** [Senparc/NeuChar#137]
https://github.com/Senparc/NeuChar/blob/eee1215b51360bca849553de42c6e1bcb894f306/src/Senparc.NeuChar/MessageHandlers/MessageHandler.cs#L575

企业微信生成联系我二维码添加外部联系时候，如果多个微信同时扫码，100%会出现（反复测试）不推送消息的情况，原因是消息去重屏蔽了消息继续向下。MsgId，TimeStamp，MsgType，CreateTime这几维度不足以判断是否为重复消息，

**Comment by JeffreySu** [comment]
@zxz524 已经发布新版本，请测试：https://github.com/Senparc/NeuChar/pull/135

**Comment by zxz524** [comment]
这是来自QQ邮箱的自动回复邮件。
 
您好，你的邮件已经收到，我会尽快给您回复。
