### ISSUE TITLE
SelectMenuKeyword中handler.SelectMenuId字符串未初始化

### ISSUE THREAD

**Issue by tongbenchuan** [Senparc/NeuChar#32]
if (!handler.MatchSuccessed &&
               ((handler.CaseSensitive && handler.SelectMenuId == finalKeyword ||
               (!handler.CaseSensitive && handler.SelectMenuId.ToUpper() == finalKeyword.ToUpper()))))
其中 handler.SelectMenuId未初始化则此步会导致服务器异常

**Comment by JeffreySu** [comment]
已在新版本中添加判断，感谢！
